sudo: false
language: node_js
node_js:
  - "4.1"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

install:
  - export CXX="g++-4.8"
  - npm install


after_install:
  - $CXX --version

script:
  - npm run lint
  - npm test
